export type SiteConfig = typeof siteConfig;

export const siteConfig = {
    name: "PlaPlan - Your Personal Travel Assistant",
    description: "Plan your next adventure with PlaPlan, generating personalized travel itineraries.",
    keywords: [
        "AI travel planner",
        "AI trip planner",
        "AI itinerary generator",
        "AI vacation planner",
        "AI travel assistant",
        "smart trip planner",
        "travel itinerary app",
        "trip planner app",
        "travel route planner",
        "day-by-day trip planner",
        "road trip planner",
        "plan your trip automatically",
        "personalized travel itinerary",
        "best travel planner app",
        "plan a trip to Portugal",
        "plan a trip to Europe",
        "travel map planner",
        "discover hidden gems",
        "travel organization app",
        "travel companion app",
        "vacation itinerary builder",
        "custom travel planner",
        "digital travel assistant",
        "AI map route planner",
        "AI-powered trip ideas",
        "smart travel itinerary",
        "trip plan generator",
        "AI trip assistant",
        "AI travel guide"
    ],
    robots: "index, follow",
    url: "https://plaplan.io",
}